In [68]:
import pandas as pd
url = 'https://github.com/HamoyeHQ/HDSC-Introduction-to-Python-for-machine-learning/files/7768140/FoodBalanceSheets_E_Africa_NOFLAG.csv'
data = pd.read_csv(url,encoding='latin-1')
print(data)

       Area Code      Area  Item Code           Item  Element Code  \
0              4   Algeria       2501     Population           511
1              4   Algeria       2501     Population          5301
2              4   Algeria       2901    Grand Total           664
3              4   Algeria       2901    Grand Total           674
4              4   Algeria       2901    Grand Total           684
...          ...       ...        ...            ...           ...
60938        181  Zimbabwe       2899  Miscellaneous          5142
60939        181  Zimbabwe       2899  Miscellaneous           645
60940        181  Zimbabwe       2899  Miscellaneous           664
60941        181  Zimbabwe       2899  Miscellaneous           674
60942        181  Zimbabwe       2899  Miscellaneous           684

                                      Element             Unit     Y2014  \
0               Total Population - Both sexes     1000 persons  38924.00
1                    Domestic supply quantity      1000 tonnes      0.00
2               Food supply (kcal/capita/day)  kcal/capita/day   3377.00
3      Protein supply quantity (g/capita/day)     g/capita/day     94.90
4          Fat supply quantity (g/capita/day)     g/capita/day     80.06
...                                       ...              ...       ...
60938                                    Food      1000 tonnes     42.00
60939     Food supply quantity (kg/capita/yr)               kg      3.06
60940           Food supply (kcal/capita/day)  kcal/capita/day      3.00
60941  Protein supply quantity (g/capita/day)     g/capita/day      0.10
60942      Fat supply quantity (g/capita/day)     g/capita/day      0.04

          Y2015     Y2016     Y2017     Y2018
0      39728.00  40551.00  41389.00  42228.00
1          0.00      0.00      0.00      0.00
2       3379.00   3372.00   3341.00   3322.00
3         94.35     94.72     92.82     91.83
4         79.36     77.40     80.19     77.28
...         ...       ...       ...       ...
60938     46.00     33.00     19.00     16.00
60939      3.33      2.35      1.33      1.08
60940      4.00      3.00      1.00      1.00
60941      0.11      0.08      0.04      0.04
60942      0.05      0.03      0.02      0.01

[60943 rows x 12 columns]

In [69]:
S = [['him', 'sell'], [90, 28, 43]]

print(S[0][1][1])

e

In [70]:
my_tuppy = (1,2,5,8)

my_tuppy[2] = 6

TypeError: 'tuple' object does not support item assignment

In [71]:
lst = [[35, 'Portugal', 94], [33, 'Argentina', 93], [30 , 'Brazil', 92]]

col = ['Age','Nationality','Overall']
da = pd.DataFrame(lst,columns = col,index = [i for i in range(1,4)])
print(da)

   Age Nationality  Overall
1   35    Portugal       94
2   33   Argentina       93
3   30      Brazil       92

In [72]:
data.groupby('Element')['Y2017'].sum()

Element
Domestic supply quantity                  2088198.10
Export Quantity                            182338.80
Fat supply quantity (g/capita/day)          10253.84
Feed                                       223705.68
Food                                      1258888.28
Food supply (kcal/capita/day)              454681.00
Food supply quantity (kg/capita/yr)         48690.04
Import Quantity                            294559.09
Losses                                     160614.00
Other uses (non-food)                       91645.97
Processing                                 292836.00
Production                                2030056.89
Protein supply quantity (g/capita/day)      11842.45
Residuals                                   35500.00
Seed                                        24870.14
Stock Variation                             54316.91
Total Population - Both sexes             1112641.00
Tourist consumption                            91.00
Name: Y2017, dtype: float64

In [81]:
data.iloc[:]

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28
...,...,...,...,...,...,...,...,...,...,...,...,...
60938,181,Zimbabwe,2899,Miscellaneous,5142,Food,1000 tonnes,42.00,46.00,33.00,19.00,16.00
60939,181,Zimbabwe,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,3.06,3.33,2.35,1.33,1.08
60940,181,Zimbabwe,2899,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,3.00,4.00,3.00,1.00,1.00
60941,181,Zimbabwe,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.10,0.11,0.08,0.04,0.04
60942,181,Zimbabwe,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.04,0.05,0.03,0.02,0.01

In [80]:
y = [(2, 4), (7, 8), (1, 5, 9)]
y[1][1]

8

In [73]:
data.groupby('Element')[['Y2014','Y2015','Y2016','Y2017']].sum()

,Y2014,Y2015,Y2016,Y2017
Element,,,,
Domestic supply quantity,1996716.35,2021493.55,2044842.70,2088198.10
Export Quantity,150020.64,157614.47,151920.46,182338.80
Fat supply quantity (g/capita/day),10225.56,10235.74,10102.77,10253.84
Feed,216927.89,225050.22,228958.65,223705.68
Food,1212332.49,1232361.10,1247022.17,1258888.28
Food supply (kcal/capita/day),454257.00,453383.00,451810.00,454681.00
Food supply quantity (kg/capita/yr),49650.63,49345.13,48985.28,48690.04
Import Quantity,274144.48,267018.46,286582.78,294559.09
Losses,153223.00,155439.00,157787.00,160614.00
Other uses (non-food),78718.13,66254.41,69563.68,91645.97
Processing,282923.00,287929.00,280631.00,292836.00
Production,1931287.75,1947019.39,1943537.15,2030056.89
Protein supply quantity (g/capita/day),11836.46,11833.95,11779.69,11842.45
Residuals,30149.00,30045.00,37224.00,35500.00
Seed,21922.92,23976.82,23389.20,24870.14
Stock Variation,58749.83,34910.99,33140.12,54316.91
Total Population - Both sexes,1031585.00,1058081.00,1085107.00,1112641.00
Tourist consumption,416.00,349.00,89.00,91.00

In [75]:
data['Y2017'].mean().round(2)

140.92

In [74]:
data['Y2017'].std().round(2)

1671.86

In [76]:
import numpy as np

In [77]:
data["Area"].nunique()

49

In [79]:
data[data['Area'].isin(["Madagascar"])].groupby('Element')["Y2015"].sum()

Element
Domestic supply quantity                  31214.98
Export Quantity                             494.75
Fat supply quantity (g/capita/day)           91.85
Feed                                       2070.22
Food                                      21120.65
Food supply (kcal/capita/day)              7685.00
Food supply quantity (kg/capita/yr)         871.59
Import Quantity                            1721.80
Losses                                     2176.00
Other uses (non-food)                      3957.12
Processing                                 1803.00
Production                                29482.89
Protein supply quantity (g/capita/day)      173.05
Residuals                                  -616.00
Seed                                        699.00
Stock Variation                            -505.00
Total Population - Both sexes             24234.00
Name: Y2015, dtype: float64

In [78]:
missing_data_2014 = np.array([data['Y2014'].isnull().sum().sum(), (data['Y2014'].isnull().sum().sum() / data['Y2014'].size) * 100])
print(missing_data_2014)

[1589.            2.60735441]